//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int IdDocumento { get; set; }
        public string Documento1 { get; set; }
        public int IdPessoa { get; set; }
        public short IdTipoDocumento { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual tipodocumento tipodocumento { get; set; }
    }
}
