//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public int IdEndereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Logradouro { get; set; }
        public short Numero { get; set; }
        public int IdPessoa { get; set; }
        public short IdTipoLogradouro { get; set; }
        public string UF { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual tipo_logradouro tipo_logradouro { get; set; }
        public virtual uf uf1 { get; set; }
    }
}
