//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_venda
    {
        public long PrecoVenda { get; set; }
        public short Quantidade { get; set; }
        public int IdProduto { get; set; }
        public int IdVenda { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual venda venda { get; set; }
    }
}
