//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sigamesEntities : DbContext
    {
        public sigamesEntities()
            : base("name=sigamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<documento> documento { get; set; }
        public DbSet<endereco> endereco { get; set; }
        public DbSet<fornecedor> fornecedor { get; set; }
        public DbSet<item_venda> item_venda { get; set; }
        public DbSet<parcela> parcela { get; set; }
        public DbSet<parcela_venda> parcela_venda { get; set; }
        public DbSet<pessoa> pessoa { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<telefone> telefone { get; set; }
        public DbSet<tipo_logradouro> tipo_logradouro { get; set; }
        public DbSet<tipo_telefone> tipo_telefone { get; set; }
        public DbSet<tipodocumento> tipodocumento { get; set; }
        public DbSet<uf> uf { get; set; }
        public DbSet<venda> venda { get; set; }
    }
}
