//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parcela
    {
        public parcela()
        {
            this.parcela_venda = new HashSet<parcela_venda>();
        }
    
        public short IdParcela { get; set; }
        public long ValorParcela { get; set; }
    
        public virtual ICollection<parcela_venda> parcela_venda { get; set; }
    }
}
