//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.item_venda = new HashSet<item_venda>();
            this.fornecedor = new HashSet<fornecedor>();
        }
    
        public int IdProduto { get; set; }
        public string Nome { get; set; }
        public double PrecoUnitario { get; set; }
        public string TipoProduto { get; set; }
    
        public virtual ICollection<item_venda> item_venda { get; set; }
        public virtual ICollection<fornecedor> fornecedor { get; set; }
    }
}
