//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_logradouro
    {
        public tipo_logradouro()
        {
            this.endereco = new HashSet<endereco>();
        }
    
        public short IdTipoLogradouro { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<endereco> endereco { get; set; }
    }
}
