//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_telefone
    {
        public tipo_telefone()
        {
            this.telefone = new HashSet<telefone>();
        }
    
        public short IdTipoTelefone { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<telefone> telefone { get; set; }
    }
}
