//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipodocumento
    {
        public tipodocumento()
        {
            this.documento = new HashSet<documento>();
        }
    
        public short IdTipoDocumento { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<documento> documento { get; set; }
    }
}
