//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public venda()
        {
            this.item_venda = new HashSet<item_venda>();
            this.parcela_venda = new HashSet<parcela_venda>();
        }
    
        public int IdVenda { get; set; }
        public System.DateTime DataVenda { get; set; }
        public Nullable<int> ClientePessoaIdPessoa { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<item_venda> item_venda { get; set; }
        public virtual ICollection<parcela_venda> parcela_venda { get; set; }
    }
}
